spring.application.name=green
spring.datasource.url=jdbc:h2:mem:greendb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.security.user.name=vikas
spring.security.user.password=pass
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
